CICS-CUNOC-USAC/app-estudiantes-frontend

- .idea/.gitignore
- .idea/app-cics-nuxt.iml
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/modules.xml
- .idea/vcs.xml
- .idea/watcherTasks.xml
- app.vue
- assets/styles/main.scss
- components/SidebarNavigator.vue
- layouts/default.vue
- nuxt.config.ts
- pages/about.vue
- pages/home.vue
- pages/index.vue
- Base nuxt layout created
- Created sidebar component (missing pages)
> Create base layout and create sidebar component

- app/assets/styles/main.scss
- app/components/partials/GeneralSnackbar.vue
- app/layouts/admin.vue
- app/layouts/dashboard.vue
- app/layouts/default.vue
- app/layouts/empty.vue
- app/middleware/auth.global.ts
- app/stores/regular-auth.ts
- app/stores/snackbar.ts
- Created GeneralSnackbar component to use in all pages
- Added mentionted component to all layouts
- Created snackbar store and actions
> feat: General snackbar for showing errors, messages and warnings

- app/components/dialogs/courses/CourseDialog.vue
- app/components/progress/PensumProgressDetails.vue
- app/components/progress/PensumsCard.vue
- app/pages/dashboard/pensum/progress.vue
- app/stores/courses.ts
- app/stores/regular-career-progress.ts
- Updated Course dialog implementation
> feat: Course dialog

- app/app.vue
- app/components/profile/PersonalInfoForm.vue
- app/components/profile/details/PersonalInfoDetails.vue
- app/pages/dashboard/profile/index.vue
- package-lock.json
- package.json
- Updated project Nuxt version and packages versions (using `nuxi` CLI | [Nuxt Blog v3.8](https://nuxt.com/blog/v3-8))
> build: Updated Nuxt version and packages

- app/components/admin/staffs/StaffsView.vue
- app/components/dialogs/admin/staffs/StaffDialog.vue
- app/components/dialogs/admin/staffs/StaffRolesDialog.vue
- app/components/forms/accounts/SignupForm.vue
- app/components/forms/admin/staffs/StaffForm.vue
- app/components/partials/AdminNavigator.vue
- app/components/partials/DashboardNavigator.vue
- app/components/profile/PersonalInfoForm.vue
- app/pages/admin/library/edit/[libraryItemId].vue
- app/pages/admin/thesis/index.vue
- app/pages/admin/users/index.vue
- app/stores/admin-staffs.ts
- app/stores/staff-auth.ts
- app/utils/error-converter.ts
- nuxt.config.ts
- Created admin page for managing staff type users
> feat: Staff management flow

- app/components/admin/library/LibraryView.vue
- app/components/dashboard/UserLibraryView.vue
- app/components/dialogs/admin/library/NewLibraryItemDialog.vue
- app/components/partials/AdminNavigator.vue
- app/components/partials/DashboardNavigator.vue
- app/components/partials/SidebarNavigator.vue
- app/components/portal/ManualsView.vue
- app/pages/admin/books/edit/[bookId].vue
- app/pages/admin/books/index.vue
- app/pages/admin/library/index.vue
- app/pages/admin/manuals/index.vue
- app/pages/admin/me.vue
- app/pages/dashboard/books/[bookId].vue
- app/pages/dashboard/books/index.vue
- app/stores/admin-library.ts
- app/stores/user-library.ts
- Added library section to admin panel (and its components)
- Added library page to only signed up users and downloads
> feat: Library for admin and regular users

- app/layouts/default.vue
- app/pages/portal/general/pensums/[nombreCarrera]-[codigoCarrera].vue
- package-lock.json
- package.json
- Update Nuxt and dependencies
> build: Nuxt update and dependencies

- app/app.vue
- app/components/cards/InfoCard.vue
- app/components/forms/accounts/LoginForm.vue
- app/components/partials/DashboardNavigator.vue
- app/components/partials/SidebarNavigator.vue
- app/layouts/default.vue
- app/pages/portal/extras/config.vue
- app/plugins/vuetify.ts
- app/stores/config.ts
- app/utils/themes/themes.ts
Implemented themes using vuetiy's theming features
> feat: Implement general application themes

- app/components/cards/InfoCard.vue
- app/components/partials/SidebarNavigator.vue
- app/components/portal/OfficialPostsInfiniteView.vue
- app/components/portal/OfficialPostsView.vue
- app/pages/index.vue
- app/pages/portal/general/publicaciones.vue
- app/pages/portal/post/[postId]/[postSlug]/index.vue
- app/server/api/official-post-detail/[postId]/[postSlug].ts
- app/server/api/official-posts.ts
> feat: Official posts scraping

- app/pages/portal/post/[postId]/[postSlug]/index.vue
Actualización de CSS, en la vista móvil de las Publicaciones Oficiales
> Update CSS style on interface, bug in padding "Publicaciones Oficiales"

- app/pages/portal/general/cursos/programa/[cursoId].vue
> fix: Fix pdfurl prop to show pdf in [cursoId].vue

- app/app.vue
- app/assets/styles/main.scss
- app/components/cards/InfoCard.vue
- app/components/extras/in-construction.vue
- app/components/forms/accounts/LoginForm.vue
- app/components/forms/accounts/SignupForm.vue
- app/components/partials/AdminNavigator.vue
- app/components/partials/DashboardNavigator.vue
- app/components/partials/GeneralSnackbar.vue
- app/components/partials/SidebarNavigator.vue
- app/components/profile/PasswordProfileForm.vue
- app/components/profile/PersonalInfoForm.vue
- app/layouts/admin.vue
- app/layouts/dashboard.vue
- app/layouts/default.vue
- app/layouts/empty.vue
- app/utils/themes/themes.ts
Started refactoring script in components and pages from option to composition API
> refactor: Initial refactoring from option to composition API in all pages and components

- app/assets/css/tailwind.css
- app/components.d.ts
- app/components/partials/navigation/TopNavDesktopDashboard.vue
- app/components/portal/ProgramsView.vue
- app/components/primitives/button/CButton.vue
- app/components/primitives/form/CInputText.vue
- app/pages/portal/general/cursos/programas.vue
- tailwind.config.js
- Update programs view with new UI component libraries
> refactor: Programs view

- app/components.d.ts
- app/components/forms/accounts/SignupForm.vue
- app/components/partials/SidebarNavigator.vue
- app/components/primitives/button/CButton.vue
- app/components/primitives/form/CInputText.vue
- app/components/primitives/form/CSelect.vue
- app/layouts/default.vue
- app/pages/admin/login.vue
- app/pages/portal/extras/config.vue
- app/pages/sign-up.vue
- app/stores/config.ts
- app/stores/regular-auth.ts
- package-lock.json
- package.json
> refactor: Sign up and forms

- app/app.vue
- app/content/associations/aeio.md
- app/content/associations/cics.md
- app/pages/portal/asociaciones/aeio.vue
- app/pages/portal/asociaciones/cics.vue
- app/pages/portal/general/faq-primer-ingreso.vue
- app/pages/portal/general/faq.vue
- app/pages/portal/recursos/manuales/[manualId].vue
- nuxt.config.ts
> content: Update associations

- app/app.vue
> fix: Add missing OG properties to SEO metadata

- app/pages/admin/books/create.vue
> fix: add placeholder to availabilities

- nuxt.config.ts
> feat: disable CSS minification in build configuration to fix missing prod styles

- content/associations/cics.md
> fix: Update committee members and roles for 2025-2026 period

- app/components/portal/OfficialPostsView.vue
- nuxt.config.ts
Disable SSR on main page to avoid problems with Engineering page failures
> Fix SSR problem

- app/components/forms/accounts/SignupForm.vue
- app/stores/regular-auth.ts
> refactor: add username sending to backend

- app/components/portal/OfficialPostsInfiniteView.vue
- app/components/portal/OfficialPostsView.vue
> feat: add caching mechanism for official posts data fetching

- app/app.vue
- app/composables/strapiFetch.ts
- app/lib/api/strapi/types.ts
- app/pages/portal/extras/about.vue
- app/pages/portal/recursos/manuales/[slug].vue
- app/pages/portal/recursos/manuales/index.vue
- nuxt.config.ts
- package-lock.json
- package.json
> feat: Add Strapi connection and content related dependencies

- app/app.vue
- app/components/portal/OfficialPostsInfiniteView.vue
- app/layouts/default.vue
- app/pages/portal/general/publicaciones.vue
> fix: Use keepalive to preserve infinite loading state

- app/assets/css/main.css
> fix: Add rich text content styles to styles entry point file
